# Generated by Django 5.0.6 on 2024-05-29 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='rating',
        ),
        migrations.AddField(
            model_name='drink',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.drink')),
            ],
        ),
    ]
