# Generated by Django 5.0.6 on 2024-06-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_flavor_strength_remove_drink_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='drink',
        ),
        migrations.AddField(
            model_name='drink',
            name='flavors',
            field=models.ManyToManyField(null=True, to='cocktails.flavor'),
        ),
        migrations.AddField(
            model_name='drink',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cocktails.strength'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='DrinkIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.drink')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(null=True, through='cocktails.DrinkIngredient', to='cocktails.ingredient'),
        ),
    ]
